/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author laispaivaportela
 */
import java.awt.Color;
import java.awt.Cursor;
import java.awt.Font;
import javax.swing.BorderFactory;
import javax.swing.JButton;
import javax.swing.border.EmptyBorder;
import model.Pasta;
import dao.CardsDAO;
import java.sql.SQLException;
import java.util.List;
import model.Card;

public class FrmCard extends javax.swing.JFrame {

    private String frente;
    private String verso;
    private Pasta pasta;
    private List<Card> cards;       //lista de flashcards da pasta
    private int indexAtual = 0;     //controla o índice do card atual

    //começa a sessão
    public void comeca(Pasta pasta) throws SQLException {
        this.cards = CardsDAO.cardsNaPasta(pasta);
        this.indexAtual = 0;

        if (cards.isEmpty()) {
            txtTexto.setText("Não há flashcards nesta pasta.");
            BtnFrente.setEnabled(false);
            BtnVerso.setEnabled(false);
            BtnProximo.setEnabled(false);
            BtnAnterior.setEnabled(false);
        } else {
            exibirCardAtual();
        }
    }
    
    //exibe card escolhido
    private void exibirCardAtual() {
        if (indexAtual >= 0 && indexAtual < cards.size()) {
            Card atual = cards.get(indexAtual);
            frente = atual.getFrente();
            verso = atual.getVerso();
            txtTexto.setText(frente); // Começa mostrando a frente
        }
    }
    
    //getters e setters
    public String getFrente() {
        return frente;
    }

    public void setFrente(String frente) {
        this.frente = frente;
    }

    public String getVerso() {
        return verso;
    }

    public void setVerso(String verso) {
        this.verso = verso;
    }

    /**
     * Creates new form FrmCard
     */
    public FrmCard() {
        initComponents();
        customizeUI();
    }

    //customização personalizada
    private void customizeUI() {
        //configura o frame
        getContentPane().setBackground(new Color(245, 245, 250));
        setTitle("Flashcards");

        //estiliza os botões 
        styleButton(BtnFrente, new Color(70, 130, 180)); // Azul aço
        styleButton(BtnVerso, new Color(100, 149, 237)); // Azul claro
        styleButton(BtnAnterior, new Color(169, 169, 169)); // Cinza
        styleButton(BtnProximo, new Color(60, 179, 113)); // Verde médio

        //estilização a text area
        txtTexto.setBorder(new EmptyBorder(20, 20, 20, 20));
        txtTexto.setBackground(new Color(255, 255, 245));
        txtTexto.setForeground(new Color(50, 50, 50));

        //ajeita o scroll pane
        jScrollPane1.setBorder(BorderFactory.createEmptyBorder());
        jScrollPane1.getViewport().setBackground(new Color(255, 255, 245));
    }

    //estiliza o botão
    private void styleButton(JButton button, Color color) {
        button.setBackground(color);
        button.setForeground(Color.WHITE);
        button.setFont(new Font("Segoe UI", Font.PLAIN, 18));
        button.setFocusPainted(false);
        button.setBorder(BorderFactory.createEmptyBorder(10, 20, 10, 20));
        button.setCursor(new Cursor(Cursor.HAND_CURSOR));

        //faz o efeito hover
        button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                button.setBackground(color.darker());
            }

            public void mouseExited(java.awt.event.MouseEvent evt) {
                button.setBackground(color);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txtTexto = new javax.swing.JTextPane();
        BtnFrente = new javax.swing.JButton();
        BtnVerso = new javax.swing.JButton();
        BtnProximo = new javax.swing.JButton();
        BtnAnterior = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setForeground(java.awt.Color.darkGray);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        txtTexto.setBackground(new java.awt.Color(255, 255, 245));
        txtTexto.setFont(new java.awt.Font("Inter 18pt", 0, 100)); // NOI18N
        jScrollPane1.setViewportView(txtTexto);

        BtnFrente.setFont(new java.awt.Font("Constantia", 0, 23)); // NOI18N
        BtnFrente.setText("Frente");
        BtnFrente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnFrenteActionPerformed(evt);
            }
        });

        BtnVerso.setFont(new java.awt.Font("Constantia", 0, 23)); // NOI18N
        BtnVerso.setText("Verso");
        BtnVerso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnVersoActionPerformed(evt);
            }
        });

        BtnProximo.setFont(new java.awt.Font("Constantia", 0, 23)); // NOI18N
        BtnProximo.setText("Proximo");
        BtnProximo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnProximoActionPerformed(evt);
            }
        });

        BtnAnterior.setFont(new java.awt.Font("Constantia", 0, 23)); // NOI18N
        BtnAnterior.setText("Anterior");
        BtnAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAnteriorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1521, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(435, 435, 435)
                        .addComponent(BtnFrente, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BtnVerso, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BtnAnterior, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BtnProximo, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 693, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnFrente, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnVerso, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnAnterior, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnProximo, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
//exibe a "frente" do flashcard
    private void BtnFrenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnFrenteActionPerformed
        txtTexto.setText(frente);
    }//GEN-LAST:event_BtnFrenteActionPerformed
//exibe o "verso" do flashcard
    private void BtnVersoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnVersoActionPerformed
        txtTexto.setText(verso);
    }//GEN-LAST:event_BtnVersoActionPerformed

    private void BtnAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAnteriorActionPerformed
       //volta para o card anterior
        if (indexAtual > 0) {
            indexAtual--;
            exibirCardAtual();
        } else {
            txtTexto.setText("Você já está no primeiro flashcard.");
        }
    }//GEN-LAST:event_BtnAnteriorActionPerformed

    //vai pro próximo flashcard
    private void BtnProximoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnProximoActionPerformed
        if (indexAtual < cards.size() - 1) {
            indexAtual++;
            exibirCardAtual();
        } else {
            txtTexto.setText("Você chegou ao final dos flashcards.");
        }
    }//GEN-LAST:event_BtnProximoActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated

    }//GEN-LAST:event_formWindowActivated

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened


    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAnterior;
    private javax.swing.JButton BtnFrente;
    private javax.swing.JButton BtnProximo;
    private javax.swing.JButton BtnVerso;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane txtTexto;
    // End of variables declaration//GEN-END:variables
}
