/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author laispaivaportela
 */
import java.awt.Color;
import java.awt.Cursor;
import java.awt.Font;
import javax.swing.BorderFactory;
import javax.swing.JButton;
import javax.swing.border.EmptyBorder;
import static main.Main.aplicacao;
import view.FrmPastas;
import view.FrmCriaPasta;
import view.FrmCardPasta;
import view.FrmSessao;
public class FrmMenu extends javax.swing.JFrame {
    //instancia outros frames
    FrmPastas pastas = new FrmPastas();
    FrmCriaPasta criarPasta = new FrmCriaPasta();
    FrmCardPasta cardPasta = new FrmCardPasta();
    FrmSessao sessao = new FrmSessao();
    
  //customização do frame
  private void customizeUI() {
        //configuração do frame
        getContentPane().setBackground(new Color(245, 247, 250));
        setTitle("flashcards baby");
        
        //estilização dos botões
        styleButton(BtnFlashcards, new Color(70, 130, 180)); // Azul
        styleButton(btnAdicionarCard, new Color(60, 179, 113)); // Verde
        styleButton(btnCards, new Color(100, 149, 237)); // Azul claro
        styleButton(btnAddPasta, new Color(255, 165, 0)); // Laranja
        styleButton(btnPastas, new Color(186, 85, 211)); // Roxo
        styleButton(jButton1, new Color(220, 20, 60)); // Vermelho
        
        //melhora o título
        jLabel1.setForeground(new Color(50, 50, 50));
    }
    //estiliza botao
    private void styleButton(JButton button, Color color) {
        button.setBackground(color);
        button.setForeground(Color.WHITE);
        button.setFont(new Font("Segoe UI", Font.BOLD, 14));
        button.setFocusPainted(false);
        button.setBorder(BorderFactory.createCompoundBorder(
            BorderFactory.createLineBorder(color.darker(), 1),
            new EmptyBorder(10, 25, 10, 25)
        ));
        button.setCursor(new Cursor(Cursor.HAND_CURSOR));
        
        //efeito hover
        button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                button.setBackground(color.brighter());
                button.setBorder(BorderFactory.createCompoundBorder(
                    BorderFactory.createLineBorder(color.brighter().brighter(), 2),
                    new EmptyBorder(10, 25, 10, 25)
                ));
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                button.setBackground(color);
                button.setBorder(BorderFactory.createCompoundBorder(
                    BorderFactory.createLineBorder(color.darker(), 1),
                    new EmptyBorder(10, 25, 10, 25)
                ));
            }
        });
    }
    /**
     * Creates new form FrmMenu
     */
    
    //construtor
    public FrmMenu() {
        initComponents();
        customizeUI();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BtnFlashcards = new javax.swing.JButton();
        btnAdicionarCard = new javax.swing.JButton();
        btnCards = new javax.swing.JButton();
        btnAddPasta = new javax.swing.JButton();
        btnPastas = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        BtnFlashcards.setText("Estudar");
        BtnFlashcards.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnFlashcardsActionPerformed(evt);
            }
        });

        btnAdicionarCard.setText("Adicionar Card");
        btnAdicionarCard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarCardActionPerformed(evt);
            }
        });

        btnCards.setText("Tabela Cards");
        btnCards.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCardsActionPerformed(evt);
            }
        });

        btnAddPasta.setText("Adicionar Pasta");
        btnAddPasta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddPastaActionPerformed(evt);
            }
        });

        btnPastas.setText("Tabela Pastas");
        btnPastas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPastasActionPerformed(evt);
            }
        });

        jButton1.setText("Tabela Card/Pasta");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 100)); // NOI18N
        jLabel1.setText("Menu");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(144, 144, 144)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(BtnFlashcards, javax.swing.GroupLayout.PREFERRED_SIZE, 524, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(btnCards, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnAdicionarCard, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(68, 68, 68)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(btnPastas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnAddPasta, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jLabel1)))
                .addContainerGap(276, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel1)
                .addGap(67, 67, 67)
                .addComponent(BtnFlashcards, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdicionarCard, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAddPasta, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnPastas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCards, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(202, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
//dependendo do botao escolhido o usuario é mandando para a tela desejada
    private void BtnFlashcardsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnFlashcardsActionPerformed
        sessao.setVisible(true);
    }//GEN-LAST:event_BtnFlashcardsActionPerformed

    private void btnAdicionarCardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarCardActionPerformed
        aplicacao.executarAcao(2);
    }//GEN-LAST:event_btnAdicionarCardActionPerformed

    private void btnCardsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCardsActionPerformed
        aplicacao.executarAcao(3);
    }//GEN-LAST:event_btnCardsActionPerformed

    private void btnAddPastaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddPastaActionPerformed
        criarPasta.setVisible(true);
    }//GEN-LAST:event_btnAddPastaActionPerformed

    private void btnPastasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPastasActionPerformed
        pastas.setVisible(true);
    }//GEN-LAST:event_btnPastasActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       cardPasta.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnFlashcards;
    private javax.swing.JButton btnAddPasta;
    private javax.swing.JButton btnAdicionarCard;
    private javax.swing.JButton btnCards;
    private javax.swing.JButton btnPastas;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
